name: tests
on:
  push:
    branches:
      - main

jobs:
  run_docs:
    name: Run tests
    runs-on: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build
      
      - name: Run tests
        run : |
          . env/bin/activate
          git lfs pull
          python -m pip install pytest-cov
          python -m pytest
          PYTORCH_JIT=0 python -m pytest --cov-report term-missing --cov=ml4opf tests/ -vv


